apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geo-api
  namespace: geo
  labels:
    app.kubernetes.io/name: geo-api
    app.kubernetes.io/part-of: geo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: api.geo.sent-tech.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geo-api
                port:
                  name: http
  tls:
    - hosts:
        - api.geo.sent-tech.ca
      secretName: geo-api-tls
