/**
 * Native-text ingestion for Longueuil's per-zone "GRILLES DES USAGES ET NORMES".
 *
 * WHY a dedicated runner (vs `zonage-norms-run.ts`):
 *   Longueuil does NOT publish a single grille PDF. It publishes ONE native-text
 *   PDF per zone (machine-generated by GemBox, identical fixed-label vertical
 *   layout) under
 *     https://geomatique.longueuil.quebec/Donnees/Zonage/<ARR>/<CODE>.pdf
 *   indexed by `GrillesUsageUrbanisme_<ARR>.html` (mirrored on Données Québec,
 *   dataset `grilles-de-specification`). The zone codes match the SIG grille
 *   already on S3 (normalized/ca-qc-zonage/qc-zonage-longueuil/…) 1:1 — modulo a
 *   "(VLO)"/"(STH)"/"(GPK)" arrondissement suffix the grille appends. That suffix
 *   makes the generic runner's cross-validation report overlap=0 and REJECT, so
 *   this runner deposits via `depositParquetOnly` directly (no manifest, the
 *   conductor reconciles).
 *
 * ANTI-INVENTION: ZERO fabrication. Every value comes from the FROZEN
 * `normalizeUnit` cell normaliser (FR comma, unit suffix, prose→null, "s.o."→null
 * NEVER 0). zone_code is read VERBATIM from the PDF's "ZONE <code>" title and
 * cross-checked against the filename. A multi-structure zone keeps the FULL
 * verbatim line in `raw`; the published `value` is the first structure column.
 * `null` always beats a fabricated norm.
 *
 * Label → schema mapping (Longueuil grille → deployed 8-norm schema):
 *   marge_avant_min   ← "Avant (m) (min/max)"               (min side, m)
 *   marge_laterale_min← "Latérale minimale (m)"             (single, m)
 *   marge_arriere_min ← "Arrière minimale (m)"              (single, m)
 *   hauteur_min/max   ← "Hauteur en mètre (min/max)" if published, else
 *                       "Hauteur en étage (min/max)"        (m / etages)
 *   frontage_min      ← Terrain "Largeur (m) (min/max)"     (min side, m)
 *   superficie_min    ← Terrain "Superficie (m²) (min/max)" (min side, m2)
 *   densite           ← "Coefficient d'emprise au sol (min/max)" (CES; max side
 *                       if published else min — a land-coverage ceiling, ratio)
 *   usages            ← the checked (✔) "X# : libellé" classes, verbatim.
 *
 * Usage (npx tsx, from acquisition/):
 *   # 1. harvest one arrondissement's per-zone PDFs (shell, parallel):
 *   #   curl the codes listed by GrillesUsageUrbanisme_<ARR>.html into <dir>
 *   # 2. ingest + deposit:
 *   tsx src/zonage-norms-longueuil-ingest.ts \
 *     --pdf-dir /path/to/vlo_pdfs --arr VLO --reglement VL-2025-839 \
 *     --source-url https://www.donneesquebec.ca/recherche/dataset/grilles-de-specification \
 *     [--snapshot 2026-06-30] [--limit N] [--dry-run]
 */
import { readdir } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import {
  normalizeUnit,
  type ZoneNormsT,
  type NormFieldT,
  type NormUnitT,
} from "../../packages/qc-sources/src/sources/grille-specifications-parser.js";

import { s3Client } from "./lib/s3.js";
import { depositParquetOnly, publishedFieldPct } from "./lib/zonage-norms.js";

const MIN_DEPOSIT_ZONE_CODES = 3;

interface Args {
  pdfDir: string;
  arr: string;
  reglement: string;
  sourceUrl: string;
  snapshot: string;
  limit?: number;
  dryRun: boolean;
}

function parseArgs(argv: string[]): Args {
  const get = (k: string): string | undefined => {
    const i = argv.indexOf(`--${k}`);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const pdfDir = get("pdf-dir");
  const arr = get("arr");
  const reglement = get("reglement");
  const sourceUrl = get("source-url");
  if (!pdfDir || !arr || !reglement || !sourceUrl) {
    throw new Error(
      "required: --pdf-dir <dir> --arr <VLO|STH|GPK> --reglement <id> --source-url <url>",
    );
  }
  return {
    pdfDir,
    arr,
    reglement,
    sourceUrl,
    snapshot: get("snapshot") ?? new Date().toISOString().slice(0, 10),
    ...(get("limit") ? { limit: Number(get("limit")) } : {}),
    dryRun: argv.includes("--dry-run"),
  };
}

function pdftotextLayout(pdfPath: string): string {
  const r = spawnSync("pdftotext", ["-q", "-layout", "-enc", "UTF-8", pdfPath, "-"], {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  if (r.status !== 0) throw new Error(`pdftotext failed (${r.status})`);
  return r.stdout ?? "";
}

interface Prov {
  source_url: string;
  methode: string;
  snapshot: string;
  page: string;
}

/** Build one NormField from a verbatim cell, keeping the FULL line in `raw`. */
function field(
  cell: string,
  fullRaw: string,
  fallbackUnit: NormUnitT,
  prov: Prov,
): NormFieldT {
  const n = normalizeUnit(cell, fallbackUnit);
  const published = n.value !== null;
  return {
    value: n.value,
    raw: fullRaw.trim(),
    unit: n.unit,
    confidence: published ? 1 : 0,
    ...(published ? {} : { flag: n.absent ? "absent" : "a-verifier" }),
    _provenance: prov,
  };
}

/** First whitespace-separated structure column of a label's remainder. */
function firstColumn(remainder: string): string {
  const cols = remainder.trim().split(/\s{2,}/).filter((c) => c.length > 0);
  return cols[0] ?? "";
}

/** Split a "min / max" first-column cell into its two verbatim sides. */
function minMax(cell: string): { min: string; max: string } {
  const i = cell.indexOf("/");
  if (i < 0) return { min: cell.trim(), max: "" };
  return { min: cell.slice(0, i).trim(), max: cell.slice(i + 1).trim() };
}

/**
 * Parse ONE Longueuil per-zone grille (native-text `pdftotext -layout`).
 * Returns null when the page carries no readable "ZONE <code>" title.
 */
export function parseLongueuilGrille(
  layoutText: string,
  meta: { source_url: string; snapshot: string; methode: string },
  expectedCode?: string,
): ZoneNormsT | null {
  const lines = layoutText.split(/\r?\n/);

  // zone_code — VERBATIM from the title; cross-check the filename when provided.
  // The règlement number sometimes wraps and glues to the title ("…839ZONE
  // H31-067"); a letter-only negative lookbehind tolerates a leading digit while
  // still refusing "ZONE" embedded in a larger word.
  let zoneCode: string | undefined;
  for (const ln of lines) {
    const m = ln.match(/(?<![A-Za-z])ZONE\s+([A-Z]{1,2}\d{1,2}-\d{1,4}[A-Z]?)\b/);
    if (m) {
      zoneCode = m[1].toUpperCase();
      break;
    }
  }
  if (!zoneCode) return null;
  if (expectedCode && zoneCode !== expectedCode.toUpperCase()) {
    // Title disagrees with the filename → do not trust (anti-invention).
    return null;
  }

  const prov: Prov = { ...meta, page: `ZONE ${zoneCode}` };

  // Map each target label to the verbatim remainder after it (first hit wins).
  const remainderAfter = (label: string): string | null => {
    for (const ln of lines) {
      const i = ln.indexOf(label);
      if (i >= 0) return ln.slice(i + label.length);
    }
    return null;
  };

  const rangeField = (
    label: string,
    side: "min" | "max",
    unit: NormUnitT,
  ): NormFieldT | null => {
    const rem = remainderAfter(label);
    if (rem === null) return null;
    const col = firstColumn(rem);
    const { min, max } = minMax(col);
    return field(side === "min" ? min : max, rem, unit, prov);
  };

  const singleField = (label: string, unit: NormUnitT): NormFieldT | null => {
    const rem = remainderAfter(label);
    if (rem === null) return null;
    return field(firstColumn(rem), rem, unit, prov);
  };

  // Hauteur: take BOTH bounds from the SAME basis so min/max never mix units.
  // Étages is the canonical column (published on virtually every Longueuil
  // grille — "1/2", "1/6", "1/3"); fall back to metres only when étages is
  // entirely absent (so we never report "6 m min / 3 étages max").
  let hauteurMin = rangeField("Hauteur en étage (min/max)", "min", "etages");
  let hauteurMax = rangeField("Hauteur en étage (min/max)", "max", "etages");
  const etagesAbsent =
    (!hauteurMin || hauteurMin.value === null) && (!hauteurMax || hauteurMax.value === null);
  if (etagesAbsent) {
    const mMin = rangeField("Hauteur en mètre (min/max)", "min", "m");
    const mMax = rangeField("Hauteur en mètre (min/max)", "max", "m");
    if ((mMin && mMin.value !== null) || (mMax && mMax.value !== null)) {
      hauteurMin = mMin;
      hauteurMax = mMax;
    }
  }

  // Densité ← Coefficient d'emprise au sol (CES, a coverage ceiling): publish the
  // max side when present (the binding constraint), else the min side. Verbatim.
  const cesRem = remainderAfter("Coefficient d'emprise au sol (min/max)");
  let densite: NormFieldT | null = null;
  if (cesRem !== null) {
    const { min, max } = minMax(firstColumn(cesRem));
    const fMax = field(max, cesRem, "ratio", prov);
    densite = fMax.value !== null ? fMax : field(min, cesRem, "ratio", prov);
  }

  // Usages: the CHECKED (✔) "X# : libellé" classes, verbatim, deduped.
  const usages: string[] = [];
  const seen = new Set<string>();
  for (const ln of lines) {
    if (!ln.includes("✔")) continue;
    const before = ln.slice(0, ln.indexOf("✔")).trimEnd();
    const m = before.match(/([A-Z]\d)\s*:\s*(.+)$/);
    if (!m) continue;
    const label = `${m[1]} : ${m[2].trim()}`.replace(/\s{2,}/g, " ");
    if (!seen.has(label)) {
      seen.add(label);
      usages.push(label);
    }
  }

  return {
    zone_code: zoneCode,
    zone_page: `ZONE ${zoneCode}`,
    usages,
    densite,
    hauteur_min: hauteurMin,
    hauteur_max: hauteurMax,
    marges: {
      avant_min: rangeField("Avant (m) (min/max)", "min", "m"),
      laterale_min: singleField("Latérale minimale (m)", "m"),
      arriere_min: singleField("Arrière minimale (m)", "m"),
    },
    frontage_min: rangeField("Largeur (m) (min/max)", "min", "m"),
    superficie_min: rangeField("Superficie (m²) (min/max)", "min", "m2"),
  };
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const methode = "native-text/longueuil-grille-vertical";

  const all = (await readdir(args.pdfDir)).filter((f) => f.toLowerCase().endsWith(".pdf"));
  all.sort();
  const files = args.limit ? all.slice(0, args.limit) : all;
  console.error(`[longueuil] arr=${args.arr} pdfs=${files.length} (of ${all.length})`);

  const zones: ZoneNormsT[] = [];
  let parsed = 0;
  let skipped = 0;
  for (const f of files) {
    const code = f.replace(/\.pdf$/i, "");
    let text: string;
    try {
      text = pdftotextLayout(join(args.pdfDir, f));
    } catch {
      skipped++;
      continue;
    }
    const z = parseLongueuilGrille(
      text,
      { source_url: args.sourceUrl, snapshot: args.snapshot, methode },
      code,
    );
    if (!z) {
      skipped++;
      continue;
    }
    zones.push(z);
    parsed++;
  }

  // Dedup by zone_code (defensive — index is already unique).
  const byCode = new Map<string, ZoneNormsT>();
  for (const z of zones) byCode.set(z.zone_code, z);
  const finalZones = [...byCode.values()];

  const uniqueCodes = finalZones.length;
  const fieldPct = publishedFieldPct(finalZones);
  console.error(
    `[longueuil] parsed=${parsed} skipped=${skipped} uniqueZoneCodes=${uniqueCodes} ` +
      `publishedFieldPct=${fieldPct}%`,
  );

  if (uniqueCodes < MIN_DEPOSIT_ZONE_CODES) {
    console.log(
      JSON.stringify({ deposited: false, reason: `below gate: ${uniqueCodes} < ${MIN_DEPOSIT_ZONE_CODES}` }),
    );
    return;
  }
  if (fieldPct === 0) {
    console.log(JSON.stringify({ deposited: false, reason: "0% published norm fields (anti-invention)" }));
    return;
  }

  if (args.dryRun) {
    console.log(
      JSON.stringify(
        {
          dryRun: true,
          arr: args.arr,
          uniqueZoneCodes: uniqueCodes,
          publishedFieldPct: fieldPct,
          sample: finalZones.slice(0, 3),
        },
        null,
        2,
      ),
    );
    return;
  }

  const s3 = s3Client();
  const { result } = await depositParquetOnly({
    s3,
    slug: "longueuil",
    zones: finalZones,
    meta: {
      source_url: args.sourceUrl,
      reglement: args.reglement,
      methode,
      snapshot: args.snapshot,
    },
  });

  console.log(
    JSON.stringify(
      {
        deposited: !result.skipped,
        key: result.key,
        rows: result.rows,
        uniqueZoneCodes: result.uniqueZoneCodes,
        publishedFieldPct: result.publishedFieldPct,
        bytes: result.bytes,
      },
      null,
      2,
    ),
  );
}

// Run the CLI only when invoked directly (so `parseLongueuilGrille` can be
// imported by tests/validators without triggering the deposit pipeline).
const invokedDirectly =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) {
  main().catch((e) => {
    console.error(e instanceof Error ? e.stack : String(e));
    process.exit(1);
  });
}
